# config.yaml for real data

# Table of samples
#samples: "../config/samples.csv"
samples: "../config/test.csv"
result_dir: "results"

# Paths
folder_shell: "/Users/cychang/Desktop/lab/rhizobia-genomics/genomics/genomics_cli"
folder_data: "/Users/cychang/Dropbox/lab/rhizobia-genomics/data"
folder_raw: "/Users/cychang/Dropbox/lab/rhizobia-genomics/data/raw"
folder_temp: "/Users/cychang/Dropbox/lab/rhizobia-genomics/data/temp"
folder_genomics: "/Users/cychang/Dropbox/lab/rhizobia-genomics/data/genomics"
